In [603]:
import pyspark

In [2]:
import numpy as np

In [581]:
from pyspark.mllib.linalg.distributed import CoordinateMatrix
from pyspark.mllib.linalg.distributed import MatrixEntry
from pyspark.sql.types import *
from operator import add
from pyspark.mllib.linalg import Vectors, ArrayType

In [4]:
minimal_fields = [ 
          StructField("author", StringType(), True),
          StructField("score", LongType(), True),
          StructField("controversiality", LongType(), True),
          StructField("subreddit", StringType(), True)]

In [5]:
sj = sqlContext.read.json("s3a://insight-ohoidn/sample3.json", StructType(minimal_fields))

In [5]:
sj.printSchema()

root
 |-- author: string (nullable = true)
 |-- score: long (nullable = true)
 |-- subreddit: string (nullable = true)



In [115]:
sj.toPandas()

author  score             subreddit
0         stunt_penguin      1            Filmmakers
1             [deleted]      2           Addons4Kodi
2                 69ing      5         NotTimAndEric
3        ArchadianJudge      2                 Saber
4              sglville      2            The_Donald
5           NEWORLDODOR      3        JordanPeterson
6             zachwad22      1             AskReddit
7       lurker4lyfe6969      2              Military
8        SuburbanStoner      2                trashy
9            ensanguine     18   KitchenConfidential
10               p-wing      3                TagPro
11            Lolonnais      2                 DotA2
12  askingquestionsblog      1      PuzzleAndDragons
13          Newbieshoes      7    SecretWorldLegends
14            sking1225      2         SquaredCircle
15   PM_ME_WEIRD_SMILES      3                Tinder
16            Alvarez09      9                buccos
17          Synchrotr0n      1                brasil
18           rudolphsb9      2              niceguys
19       arbuthnot-lane      6                Norway
20               d3fect      1         d3fecttesting
21       relator_fabula      1             NYYankees
22               Knonkh      1                  acrl
23             zxj4k3xz      2               airsoft
24            [deleted]      1                loseit
25            [deleted]      1                 women
26       mcgregorshakes      2               RoastMe
27              kamekai     21              business
28          KarlOskar12     -3             runescape
29       CrimsonStone72      6           harrypotter
30            marflow75      4          solareclipse
31             Jechtael      2                   SCP
32         ChaoticLogix      1           techsupport
33                T1PPY      3                asoiaf
34           MdMa4Me247     15                  MDMA
35           Kanyeezy96      2          RocketLeague
36             19720703     11                   sex
37         flyingmunkie      1               airsoft
38          spartag00se      1             AskReddit
39         mrhomeless97      2               Trivium
40               Asquil      2                 anime
41            [deleted]      1              politics
42         whammydiddle      2                redsox
43             horsodox      1        DebateReligion
44            [deleted]      1             AskReddit
45             telebofh     23          pcmasterrace
46     sagittariuscraig      3             Retconned
47     PM_YOUR_HARDCOCK      1       comicbookmovies
48         sarahfearing      1             AskReddit
49              twojs1b      1             AskReddit
50              EBJ1990      0         SquaredCircle
51              x00drew      1  RocketLeagueExchange
52              mikemnm      1  RocketLeagueExchange
53          Blacktivism      1               Roadcam
54          Inoidzervit      4               CatGifs
55             Astonsfw      4               Bondage
56    the_orange_wizard     19        shittankiessay
57        noonespecific     20             starbound
58            CMikeHunt      2               halifax
59           Cosmodious      2                  ADHD
                    ...    ...                   ...

[1000000 rows x 3 columns]

In [6]:
sj.registerTempTable('test')

In [943]:
sorted(range(10), key = lambda v: -v)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [52]:
sqlContext.sql('select author from test').toPandas()

author
0         stunt_penguin
1             [deleted]
2                 69ing
3        ArchadianJudge
4              sglville
5           NEWORLDODOR
6             zachwad22
7       lurker4lyfe6969
8        SuburbanStoner
9            ensanguine
10               p-wing
11            Lolonnais
12  askingquestionsblog
13          Newbieshoes
14            sking1225
15   PM_ME_WEIRD_SMILES
16            Alvarez09
17          Synchrotr0n
18           rudolphsb9
19       arbuthnot-lane
20               d3fect
21       relator_fabula
22               Knonkh
23             zxj4k3xz
24            [deleted]
25            [deleted]
26       mcgregorshakes
27              kamekai
28          KarlOskar12
29       CrimsonStone72
30            marflow75
31             Jechtael
32         ChaoticLogix
33                T1PPY
34           MdMa4Me247
35           Kanyeezy96
36             19720703
37         flyingmunkie
38          spartag00se
39         mrhomeless97
40               Asquil
41            [deleted]
42         whammydiddle
43             horsodox
44            [deleted]
45             telebofh
46     sagittariuscraig
47     PM_YOUR_HARDCOCK
48         sarahfearing
49              twojs1b
50              EBJ1990
51              x00drew
52              mikemnm
53          Blacktivism
54          Inoidzervit
55             Astonsfw
56    the_orange_wizard
57        noonespecific
58            CMikeHunt
59           Cosmodious
                    ...

[1000000 rows x 1 columns]

In [469]:
occurrences = sqlContext.sql("""
select *, dense_rank() over (order by subreddit desc) as rid 
from  (SELECT subreddit, author, sum(sign(score)) as tally,\
    count(score) as activity, dense_rank() over (order by author desc) as uid
from test
group by subreddit, author)
where tally!=0
""").persist(StorageLevel.MEMORY_AND_DISK_SER)
occurrences.registerTempTable('occurrences')

In [470]:
def df_most_active_subreddits(k = 1000):
    most_active = sqlContext.sql("""
    select * from
        (select *, dense_rank() over (order by activity desc) as ordered_id
        from (select rid, subreddit, sum(activity) as activity
            from occurrences
            group by rid, subreddit))
    where ordered_id<=%s
""" % k).persist(StorageLevel.MEMORY_AND_DISK_SER)
    most_active.registerTempTable('most_active')
    return most_active

In [475]:
max_numreddits = 100
act = df_most_active_subreddits(max_numreddits)

In [476]:
act.toPandas()

rid             subreddit  activity  ordered_id
0   16312             AskReddit     69641           1
1    2571              politics     18724           2
2   15972            BigBrother     17430           3
3    9395         SquaredCircle     14014           4
4    8796            The_Donald     11711           5
5    5120         gameofthrones     10861           6
6    3242                   nba      9613           7
7    5182                 funny      9236           8
8   10051  RocketLeagueExchange      8503           9
9     441                videos      7850          10
10    157             worldnews      7320          11
11   3995       leagueoflegends      6435          12
12   1597                soccer      5292          13
13   3349                movies      5246          14
14  14578                 DotA2      4874          15
15   9646        Showerthoughts      4824          16
16   3170                  news      4745          17
17   2691                  pics      4740          18
18   5109                gaming      4713          19
19  11995                   MMA      4414          20
20   1131             teenagers      4242          21
21    900         todayilearned      4140          22
22   4720           hearthstone      4085          23
23   2813           pathofexile      3923          24
24   2794          pcmasterrace      3778          25
25  10886       PUBATTLEGROUNDS      3769          26
26  10975             Overwatch      3721          27
27   7203              baseball      3706          28
28   7553                 anime      3704          29
29  11362             NYYankees      3636          30
30   7393                asoiaf      3608          31
31   2216         relationships      3605          32
32  10731           Philippines      3573          33
33  13999      FireEmblemHeroes      3346          34
34   3610                me_irl      3335          35
35   7291                   aww      3248          36
36   4940              gonewild      3085          37
37   6353            conspiracy      2957          38
38   5003                  gifs      2939          39
39   5245              freefolk      2918          40
40  15912    BlackPeopleTwitter      2918          40
41  14984       DBZDokkanBattle      2907          41
42   4662           hiphopheads      2887          42
43   2052       rupaulsdragrace      2762          43
44   3491     mildlyinteresting      2737          44
45  10274              Rainbow6      2675          45
46   7328             australia      2662          46
47   5618             ethtrader      2646          47
48  13525       GlobalOffensive      2617          48
49   8818          TheSilphRoad      2578          49
50   1059           thebachelor      2547          50
51  13524  GlobalOffensiveTrade      2535          51
52  15934               Bitcoin      2501          52
53   6783              buildapc      2382          53
54   1128               teenmom      2378          54
55   3150                   nfl      2279          55
56  16615                   Amd      2272          56
57   2164          rickandmorty      2162          57
58  15065         CringeAnarchy      2150          58
59   2604             pokemongo      2139          59
      ...                   ...       ...         ...

[106 rows x 4 columns]

In [477]:
def df_valid_users(min_subreddits = 2, max_subreddits = 20):
    """
    filter users by the number of subreddits they've posted in, among the above-defined most active subreddits
    """
    most_active_users = sqlContext.sql("""
    select * from
        (select author, count(subreddit) as count
        from 
            (select * from occurrences
            where subreddit in (select subreddit from most_active))
        group by author
        order by count desc)
    where count>=%d and count<=%d""" % (min_subreddits, max_subreddits)).persist(StorageLevel.MEMORY_AND_DISK_SER)
    most_active_users.registerTempTable('most_active_users')
    return most_active_users

In [495]:
act_users = df_valid_users(min_subreddits = 4)

In [496]:
act_users.toPandas()

author  count
0           JeopardyQBot     19
1             _youtubot_     18
2       Mentioned_Videos     17
3          imguralbumbot     17
4             HelperBot_     16
5            RemindMeBot     16
6             LinkFixBot     15
7        youtubefactsbot     12
8              Gyazo_Bot     11
9           timezone_bot     11
10                  up48     10
11         defiantPossum     10
12             AltimaNEO     10
13              O_Apples     10
14   AsksAStupidQuestion     10
15             Allenba77     10
16          sneakpeekbot     10
17          anti-gif-bot     10
18        DeniseDeNephew      9
19  the_leprechauns_anus      9
20      polynomialpusher      9
21         reelect_rob4d      9
22           gazongas001      9
23          MisanthropeX      8
24           spockspeare      8
25            rubermnkey      8
26    pimpmastahanhduece      8
27        flappingpiegon      8
28             RazorRush      8
29             GClooney1      8
30             DivX_Greg      8
31             wirefires      8
32                nimo01      8
33         hutchandstuff      8
34          female_lenin      8
35            chevymonza      8
36        TotesMessenger      8
37          Not_Just_You      8
38     theoptionexplicit      8
39                kuhvir      8
40          chasebrendon      8
41    SmartestIdiotAlive      8
42            SaintsNoah      8
43        One_Hot_Minute      8
44           CaptnCarl85      8
45           ArrowRobber      8
46             qe_locura      8
47  POOTER_SHOOTSQUIRTER      8
48    SeriouslyWhenIsHL3      8
49            kiwiking44      8
50           LemmysGhost      8
51   TweetsInCommentsBot      8
52             oscarveli      8
53                wpiman      7
54         redpandaeater      7
55   long_wang_big_balls      7
56             iambluest      7
57          hardspank916      7
58         doubleflusher      7
59    dickfromaccounting      7
                     ...    ...

[1369 rows x 2 columns]

In [497]:
test2 = sqlContext.sql("""
select test.author, test.score, test.controversiality, test.subreddit, most_active.ordered_id as ordered_id
from test
inner join most_active on most_active.subreddit=test.subreddit""")
test2.registerTempTable('test2')

In [498]:
occurrences_pruned = sqlContext.sql("""
select *
from  (SELECT test2.subreddit, author, test2.ordered_id, sum(score) as tally,\
    sum(abs(score)) as activity, dense_rank() over (order by author desc) as uid
    from test2
    where author in (select author from most_active_users)
    group by test2.subreddit, test2.ordered_id, author)
where tally!=0
""").persist(StorageLevel.MEMORY_AND_DISK_SER)
occurrences_pruned.registerTempTable('occurrences_pruned')

In [499]:
occurrences_pruned.toPandas()

subreddit               author  ordered_id  tally  activity  uid
0      relationships              zylithi          32      3         3    1
1        legaladvice              zylithi          67      4         4    1
2           politics              zylithi           2      1         1    1
3          AskReddit              zylithi           1     14        14    1
4         BigBrother      zotsandcrambles           3      7         7    2
5          pokemongo      zotsandcrambles          59     19        19    2
6      todayilearned      zotsandcrambles          22      8         8    2
7           freefolk      zotsandcrambles          40     10        10    2
8           politics                zetec           2     15        15    3
9                nfl                zetec          55      6        28    3
10              news                zetec          17     42        42    3
11             funny                zetec           8      2         2    3
12        neoliberal             yungkerg          83      2         2    4
13               nba             yungkerg           7    138       138    4
14       hiphopheads             yungkerg          42      1         1    4
15          politics             yungkerg           2     -8        18    4
16        television               ythms2          63      1         1    5
17       LifeProTips               ythms2          90      2         2    5
18              news               ythms2          17    166       166    5
19               MMA               ythms2          20      3         3    5
20               aww   youwontevenbelieve          36      1         1    6
21              pics   youwontevenbelieve          18      1         1    6
22         AskReddit   youwontevenbelieve           1      6         6    6
23              gifs   youwontevenbelieve          39      3         3    6
24                de      youtubefactsbot          99      9         9    7
25       teslamotors      youtubefactsbot          87      2         2    7
26          freefolk      youtubefactsbot          40      5         5    7
27         ethtrader      youtubefactsbot          47     10        10    7
28     SquaredCircle      youtubefactsbot           4     20        20    7
29        grandorder      youtubefactsbot          82      1         1    7
30          FORTnITE      youtubefactsbot          78      2         2    7
31          Warframe      youtubefactsbot          88     25        25    7
32       pathofexile      youtubefactsbot          24     10        10    7
33             ffxiv      youtubefactsbot          61      2         2    7
34     CringeAnarchy      youtubefactsbot          58     13        13    7
35  FireEmblemHeroes      youtubefactsbot          34      1         1    7
36      pcmasterrace             youshedo          25      9         9    8
37         worldnews             youshedo          11      2         2    8
38         Overwatch             youshedo          27     -2         2    8
39               WTF             youshedo          73      5         5    8
40              pics  youreabigbiasedbaby          18    128       128    9
41             funny  youreabigbiasedbaby           8     23        23    9
42              news  youreabigbiasedbaby          17     85        85    9
43              gifs  youreabigbiasedbaby          39     -1         3    9
44     OldSchoolCool  youreabigbiasedbaby          74      2         2    9
45            videos  youreabigbiasedbaby          10     12        12    9
46              news     youngjusticeperv          17      2         2   10
47          politics     youngjusticeperv           2    -15        17   10
48        The_Donald     youngjusticeperv           5     21        29   10
49        conspiracy     youngjusticeperv          38      2         2   10
50     CringeAnarchy     youngjusticeperv          58      2         2   10
51   leagueoflegends           younggun92          12      

In [501]:
bare_occurrences = sqlContext.sql("""
select ordered_id, uid, tally
from occurrences_pruned
""").persist(StorageLevel.MEMORY_AND_DISK_SER)

In [502]:
bare_occurrences.toPandas()

ordered_id  uid  tally
0           32    1      3
1           67    1      4
2            2    1      1
3            1    1     14
4            3    2      7
5           59    2     19
6           22    2      8
7           40    2     10
8            2    3     15
9           55    3      6
10          17    3     42
11           8    3      2
12          83    4      2
13           7    4    138
14          42    4      1
15           2    4     -8
16          63    5      1
17          90    5      2
18          17    5    166
19          20    5      3
20          36    6      1
21          18    6      1
22           1    6      6
23          39    6      3
24          99    7      9
25          87    7      2
26          40    7      5
27          47    7     10
28           4    7     20
29          82    7      1
30          78    7      2
31          88    7     25
32          24    7     10
33          61    7      2
34          58    7     13
35          34    7      1
36          25    8      9
37          11    8      2
38          27    8     -2
39          73    8      5
40          18    9    128
41           8    9     23
42          17    9     85
43          39    9     -1
44          74    9      2
45          10    9     12
46          17   10      2
47           2   10    -15
48           5   10     21
49          38   10      2
50          58   10      2
51          12   11      2
52          28   11     41
53          13   11     33
54           1   11      4
55          11   12     60
56           1   12      1
57           5   12      2
58          18   12     -3
59           4   13     26
           ...  ...    ...

[6540 rows x 3 columns]

### Subreddit activity:

In [738]:
df_most_active_subreddits(10).toPandas()

rid      subreddit  activity  ordered_id
0  16313      AskReddit   1143263           1
1   2571       politics    205263           2
2   5120  gameofthrones    183469           3
3    441         videos    170466           4
4  15973     BigBrother    156128           5
5    900  todayilearned    109733           6
6   3242            nba     97974           7
7   5109         gaming     95671           8
8   8796     The_Donald     94572           9
9   9396  SquaredCircle     94065          10

[10 rows x 4 columns]

In [91]:
tf_ij.entries.map(lambda entry: entry.i).distinct().count()

100

In [92]:
gf_i.numCols()

1L

In [93]:
tf_ij.numRows()

101L

In [877]:
act.toPandas()

rid             subreddit  activity  ordered_id
0   16313             AskReddit   1143263           1
1    2571              politics    205263           2
2    5120         gameofthrones    183469           3
3     441                videos    170466           4
4   15973            BigBrother    156128           5
5     900         todayilearned    109733           6
6    3242                   nba     97974           7
7    5109                gaming     95671           8
8    8796            The_Donald     94572           9
9    9396         SquaredCircle     94065          10
10    157             worldnews     92249          11
11   9647        Showerthoughts     89979          12
12   1597                soccer     89922          13
13  15913    BlackPeopleTwitter     79467          14
14   5182                 funny     71400          15
15   2052       rupaulsdragrace     56712          16
16  14579                 DotA2     56291          17
17   3995       leagueoflegends     54405          18
18  10887       PUBATTLEGROUNDS     48084          19
19   2216         relationships     47053          20
20   5003                  gifs     46354          21
21   2691                  pics     46156          22
22   7291                   aww     43756          23
23   3144              niceguys     42981          24
24   7393                asoiaf     40126          25
25   8187                   WTF     40095          26
26   7203              baseball     38205          27
27   4720           hearthstone     37550          28
28   3170                  news     37293          29
29  11996                   MMA     35231          30
30   5607                europe     33584          31
31   1128               teenmom     32340          32
32   1059           thebachelor     31172          33
33  10549        PoliticalHumor     30229          34
34  16734         AdviceAnimals     27649          35
35   3349                movies     27032          36
36   2813           pathofexile     25909          37
37   5245              freefolk     25723          38
38   7553                 anime     25234          39
39  10976             Overwatch     24048          40
40   3491     mildlyinteresting     23958          41
41   2389      quityourbullshit     23146          42
42   2164          rickandmorty     23127          43
43   3953           legaladvice     22535          44
44   3610                me_irl     22504          45
45   7328             australia     22232          46
46   6131             dankmemes     22082          47
47  13526       GlobalOffensive     22008          48
48   6973       blackpeoplegifs     21522          49
49   4662           hiphopheads     21273          50
50   4380     interestingasfuck     21146          51
51  12164           LifeProTips     19540          52
52  14000      FireEmblemHeroes     18722          53
53  13085       HumansBeingBros     18623          54
54    797                trashy     18474          55
55  11215        NintendoSwitch     18107          56
56   6353            conspiracy     17815          57
57  14203  ExpectationVsReality     17815          57
58  15066         CringeAnarchy     17384          58
59   1120            television     17248          59
      ...                   ...       ...         ...

[101 rows x 4 columns]

In [154]:
bare_occurrences.toPandas()

ordered_id  uid  tally
0           47    1     10
1           99    1      9
2           78    1      2
3           34    1      1
4           82    1      1
5           24    1     10
6           61    1      2
7           88    1     25
8           58    1     13
9           40    1      5
10          87    1      2
11           4    1     20
12          44    2      4
13           1    2      2
14          22    2      7
15          18    2      3
16           2    2      1
17           8    2      3
18          36    3     25
19          14    3      2
20          30    3    -19
21          38    3     49
22          28    3      8
23          19    3    121
24           1    4     14
25          10    4     -4
26          22    4      2
27          18    4      1
28          11    4      6
29           2    4      6
30           8    4    918
31           1    5      2
32          10    5      1
33          63    5     -3
34          16    5      4
35          18    5      2
36          76    5     10
37          40    5      6
38           8    5     16
39          44    6      3
40           1    6      4
41          35    6      1
42          16    6      1
43          57    6     19
44          76    6     84
45          40    6    207
46          67    7      5
47           1    7     14
48          10    7     40
49          97    7      8
50          22    7     15
51          17    7     31
52           8    7      1
53          36    8      2
54          66    8      6
55          99    8      1
56          17    8      1
57          16    8      1
58          11    8      2
59           2    8     17
           ...  ...    ...

[1629 rows x 3 columns]

In [998]:
%run -i linalg.py

In [ ]:
def sparse_vector_elementwise(vec, op):
    new_entries = [(i, op(val)) for i, val in zip(vec.indices, vec.values)]
    return Vectors.sparse(vec.size, new_entries)


In [1000]:
%run -i cf_numpy.py

In [793]:
test_activity_array[0]

array([ 0.47364486,  0.61937755,  0.00844025,  0.65533834,  0.77267817,
        0.37602224])

In [794]:
%run cf_numpy.py

In [1001]:
%run -i cf_spark.py

In [729]:
bare_occurrences.rdd.map(lambda row: (row.ordered_id, (row.uid, row.tally))).sortByKey().collect()

[(1, (1, 14)),
 (1, (6, 6)),
 (1, (11, 4)),
 (1, (12, 1)),
 (1, (13, 4323)),
 (1, (14, 2)),
 (1, (16, 286)),
 (1, (17, 2)),
 (1, (18, 28)),
 (1, (19, 41)),
 (1, (23, 47)),
 (1, (25, 14)),
 (1, (27, 2)),
 (1, (30, 23)),
 (1, (32, 4)),
 (1, (33, 14)),
 (1, (34, -1)),
 (1, (37, 2)),
 (1, (38, 22)),
 (1, (39, 3)),
 (1, (40, 1)),
 (1, (41, 56)),
 (1, (42, 1)),
 (1, (44, 3)),
 (1, (45, 38)),
 (1, (46, 22)),
 (1, (47, 2)),
 (1, (48, 1)),
 (1, (50, 1)),
 (1, (51, 513)),
 (1, (52, -2)),
 (1, (53, 54)),
 (1, (55, 2)),
 (1, (56, 1)),
 (1, (57, 5)),
 (1, (58, 75)),
 (1, (59, 8)),
 (1, (60, 14)),
 (1, (63, 1)),
 (1, (67, 27)),
 (1, (68, 26)),
 (1, (70, 7)),
 (1, (71, 1)),
 (1, (73, 25)),
 (1, (74, 29)),
 (1, (75, 2)),
 (1, (76, 9)),
 (1, (77, 1)),
 (1, (78, 307)),
 (1, (79, 3)),
 (1, (81, 4)),
 (1, (82, 3)),
 (1, (85, 1)),
 (1, (87, 5)),
 (1, (90, 79)),
 (1, (93, 2)),
 (1, (95, 5)),
 (1, (98, 21)),
 (1, (99, 11)),
 (1, (100, 2)),
 (1, (101, 4)),
 (1, (102, 21)),
 (1, (103, 553)),
 (1, (105, 2)),
 (

In [840]:
i_sumtally_tuples = bare_occurrences.rdd.map(lambda row: (row.ordered_id, row.tally)).sortByKey()\
.reduceByKey(add)
gf_i = CoordinateMatrix(i_sumtally_tuples.map(lambda entry: (entry[0] - 1, 0, entry[1])))

# subreddit-activity matrix
tf_ij = CoordinateMatrix(bare_occurrences.rdd.map(lambda row: (row.ordered_id, (row.uid, row.tally))).sortByKey()\
.map(lambda entry: (entry[0] - 1, entry[1][0], entry[1][1])))
nusers = tf_ij.numCols()

p_ij = coordinate_matrix_elementwise_vector_division(tf_ij, gf_i)

# TODO figure out nan issues
logp_ij = coordinateMatrixElementwise(p_ij, lambda elt: np.log((abs(elt))/np.log(nusers)))

entropy_i = coordinateMatrixElementwise(coordinate_matrix_sumj(logp_ij), lambda elt: elt + 1) # + 1, but this has to be handled separately to conserve matrix sparsity

In [602]:
p_ij.numRows()

101L

In [506]:
tf_ij.numRows()

101L

In [504]:
def transform_tf_if(val):
    newval = np.log(np.abs(val) + 1)
    if val < 0:
        return -newval
    else:
        return newval

# TODO: maybe save this for later, when noise can be reduced via dimensionality reduction
log_tf_ij = coordinateMatrixElementwise(tf_ij, transform_tf_if)

a_ij = coordinatematrix_multiply_vector_elementwise(log_tf_ij, entropy_i)

In [37]:
def predict_nobias(ratings, similarity, kind='user'):
    if kind == 'user':
        user_bias = ratings.mean(axis=1)
        ratings = (ratings - user_bias[:, np.newaxis]).copy()
        pred = similarity.dot(ratings) / np.array([np.abs(similarity).sum(axis=1)]).T
        pred += user_bias[:, np.newaxis]
    elif kind == 'item':
        item_bias = ratings.mean(axis=0)
        ratings = (ratings - item_bias[np.newaxis, :]).copy()
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
        pred += item_bias[np.newaxis, :]
        
    return pred

In [93]:
def predict_topk(ratings, similarity, kind='user', k=40):
    pred = np.zeros(ratings.shape)
    if kind == 'user':
        for i in xrange(ratings.shape[0]):
            top_k_users = [np.argsort(similarity[:,i])[:-k-1:-1]]
            for j in xrange(ratings.shape[1]):
                pred[i, j] = similarity[i, :][top_k_users].dot(ratings[:, j][top_k_users]) 
                pred[i, j] /= np.sum(np.abs(similarity[i, :][top_k_users]))
    if kind == 'item':
        for j in xrange(ratings.shape[1]):
            top_k_items = [np.argsort(similarity[:,j])[:-k-1:-1]]
            for i in xrange(ratings.shape[0]):
                pred[i, j] = similarity[j, :][top_k_items].dot(ratings[i, :][top_k_items].T) 
                pred[i, j] /= np.sum(np.abs(similarity[j, :][top_k_items]))        
    
    return pred

In [38]:
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    # Ignore nonzero terms.
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)

In [903]:
subreddit_mapper = dict(act.rdd.map(lambda entry: (entry.ordered_id, entry.subreddit)).collect())
idx_mapper = {v: k for k, v in subreddit_mapper.iteritems()}

def notebook_idx_to_subreddit(idx):
    return subreddit_mapper[idx + 1]

def notebook_subreddit_to_idx(sub):
    return idx_mapper[sub] - 1

In [901]:
def top_k_movies(similarity, movie_idx, k=6):
    return [notebook_idx_to_subreddit(x) for x in np.argsort(similarity[movie_idx,:])[:-k-1:-1]]

In [68]:
get_mse(predict_nobias, test)

TypeError: 'function' object has no attribute '__getitem__'

In [843]:
np.ones((2, 2)).dot(np.ones((2, 1)))

array([[ 2.],
       [ 2.]])

In [756]:
bare_occurrences.toPandas()

rid     uid  tally
0     1  173573      1
1     2    2510      1
2     3  202843      1
3     4   71343      2
4     5  157008      1
5     6   22113      2
6     6   29476     11
7     6   41712      6
8     6   52207      4
9     6   68993      9
10    6   72151      2
11    6   73394      1
12    6   99328      2
13    6  107223      1
14    6  157950     13
15    6  158256      6
16    6  161058     14
17    6  164299      9
18    6  167056     57
19    6  170651      4
20    6  182984     14
21    6  190719      5
22    6  204970      1
23    6  212901      4
24    6  219743      5
25    6  224240      1
26    6  245974     10
27    6  247719      9
28    6  250489      5
29    6  263115     17
30    6  269211      4
31    6  270545      6
32    6  281333     25
33    6  281404     19
34    6  282960      3
35    6  289078      1
36    6  294241      1
37    6  303966      5
38    6  309368      3
39    6  312009      5
40    6  312679      8
41    6  316296      2
42    6  335521      1
43    7   21702      4
44    7  116855      4
45    7  131891      3
46    7  136727      5
47    7  157950      2
48    7  326961      1
49    7  331361     12
50    7  338770      1
51    8     671      6
52    8  125324      3
53    9    4123      3
54    9  157950      1
55   10  189373      3
56   11   90933      1
57   11  223242      3
58   11  243839      1
59   12   22678      3
    ...     ...    ...

[465503 rows x 3 columns]

In [796]:
a_ij.numCols()

57010L

In [350]:
np.mean(ndmat, axis = 0).shape

(100,)

In [799]:
ndmat = coordinate_matrix_to_ndarr(tf_ij)
#ndmat/=np.mean(ndmat)
ndmat = ndmat.T
ndmat = ndmat[1:, 1:]
train, test = train_test_split(ndmat)
similarity = fast_similarity(train)

sim [[  1.00000000e+00   1.00000000e-09   1.50000000e+01 ...,   1.00000000e-09
    1.00000000e-09   1.00000000e-09]
 [  1.00000000e-09   4.90000000e+01   1.00000000e-09 ...,   1.00000000e-09
    1.00000000e-09   1.00000000e-09]
 [  1.50000000e+01   1.00000000e-09   2.25000000e+02 ...,   1.00000000e-09
    1.00000000e-09   1.00000000e-09]
 ..., 
 [  1.00000000e-09   1.00000000e-09   1.00000000e-09 ...,   1.00000000e+00
    1.00000000e-09   1.00000000e-09]
 [  1.00000000e-09   1.00000000e-09   1.00000000e-09 ...,   1.00000000e-09
    1.00000000e+00   1.00000000e-09]
 [  1.00000000e-09   1.00000000e-09   1.00000000e-09 ...,   1.00000000e-09
    1.00000000e-09   4.90000000e+01]]
diag [   1.   49.  225. ...,    1.    1.   49.]
[[  1.   7.  15. ...,   1.   1.   7.]]


In [919]:
import matplotlib.pyplot as plt

In [916]:
np.min(np.abs(similarity))

4.1997201680174538e-13

In [932]:
%run linalg.py

In [931]:
test_multiply()

In [854]:
sim = similarity_matrix(ndarr_to_coord_array(ndmat.T))

In [948]:
sim.entries.partitions

AttributeError: 'PipelinedRDD' object has no attribute 'partitions'

In [977]:
simnd = coordinate_matrix_to_ndarr(sim)

In [980]:
coordinate_matrix_to_ndarr(ndarr_to_coord_array(simnd))

array([[  1.00000000e+00,   2.25657762e-03,   1.84108404e-03, ...,
          1.57202666e-04,   3.79941463e-04,   7.64723429e-04],
       [  2.25657762e-03,   1.00000000e+00,   0.00000000e+00, ...,
          6.06630720e-04,   1.91123588e-02,   1.96866281e-05],
       [  1.84108404e-03,   0.00000000e+00,   1.00000000e+00, ...,
          1.01492667e-01,   0.00000000e+00,   1.44162925e-02],
       ..., 
       [  1.57202666e-04,   6.06630720e-04,   1.01492667e-01, ...,
          1.00000000e+00,   4.75709157e-03,   0.00000000e+00],
       [  3.79941463e-04,   1.91123588e-02,   0.00000000e+00, ...,
          4.75709157e-03,   1.00000000e+00,   6.35678566e-05],
       [  7.64723429e-04,   1.96866281e-05,   1.44162925e-02, ...,
          0.00000000e+00,   6.35678566e-05,   1.00000000e+00]])

In [982]:
simnd

array([[  1.00000000e+00,   2.25657762e-03,   1.84108404e-03, ...,
          1.57202666e-04,   3.79941463e-04,   7.64723429e-04],
       [  2.25657762e-03,   1.00000000e+00,   0.00000000e+00, ...,
          6.06630720e-04,   1.91123588e-02,   1.96866281e-05],
       [  1.84108404e-03,   0.00000000e+00,   1.00000000e+00, ...,
          1.01492667e-01,   0.00000000e+00,   1.44162925e-02],
       ..., 
       [  1.57202666e-04,   6.06630720e-04,   1.01492667e-01, ...,
          1.00000000e+00,   4.75709157e-03,   0.00000000e+00],
       [  3.79941463e-04,   1.91123588e-02,   0.00000000e+00, ...,
          4.75709157e-03,   1.00000000e+00,   6.35678566e-05],
       [  7.64723429e-04,   1.96866281e-05,   1.44162925e-02, ...,
          0.00000000e+00,   6.35678566e-05,   1.00000000e+00]])

In [994]:
np.argsort(simnd)[:, :][0][::-1]

array([ 0, 39,  9, 62, 13, 91, 18,  3, 38, 43, 76, 12,  7, 21, 73, 10, 51,
       26, 22, 23, 72, 89, 31, 16, 70, 74, 27, 54, 56, 75, 15, 64, 68, 35,
       14, 61, 32,  1, 96, 57,  2, 25, 71,  4, 30, 36, 28, 77, 55, 78, 24,
       17, 19, 82, 66, 99, 20, 84, 93, 63, 44,  5, 11, 98, 45, 37, 85, 90,
       69, 48, 34, 95, 97, 33, 52, 47,  6, 83, 58, 60, 88, 49, 42, 41, 92,
       87,  8, 29, 46, 94, 80, 86, 59, 81, 40, 79, 67, 53, 50, 65])

In [976]:
np.argsort(test_arr)

array([[9, 8, 7, 6, 5, 0, 1, 2, 3, 4]])

In [983]:
test_arr = np.array([[1, 2, 3, 4, 5, -1, -2, -3, -4, -5], range(10)])

In [997]:
np.array(sim.entries.map(lambda x: (x.i, [(x.j, x.value)]))\
.reduceByKey(add)\
.map(lambda row: map(lambda tup: tup[0], sorted(row[1], key = lambda tup: -tup[1]))[:10])\
.collect())

array([[0L, 39L, 9L, 62L, 13L, 91L, 18L, 3L, 38L, 43L],
       [72L, 6L, 27L, 7L, 25L, 94L, 18L, 35L, 1L, 10L],
       [1L, 91L, 16L, 15L, 39L, 10L, 6L, 7L, 98L, 13L],
       [73L, 38L, 70L, 29L, 25L, 96L, 9L, 0L, 84L, 43L],
       [74L, 30L, 78L, 66L, 36L, 31L, 99L, 38L, 48L, 43L],
       [2L, 49L, 97L, 27L, 54L, 6L, 58L, 99L, 71L, 25L],
       [75L, 84L, 56L, 27L, 39L, 55L, 93L, 37L, 33L, 40L],
       [3L, 97L, 41L, 28L, 91L, 85L, 11L, 71L, 4L, 56L],
       [76L, 39L, 19L, 70L, 0L, 43L, 34L, 5L, 2L, 61L],
       [4L, 62L, 65L, 96L, 3L, 10L, 51L, 91L, 26L, 13L],
       [5L, 60L, 86L, 51L, 19L, 59L, 49L, 39L, 16L, 22L],
       [77L, 87L, 23L, 86L, 46L, 90L, 60L, 3L, 65L, 47L],
       [78L, 43L, 74L, 20L, 7L, 35L, 51L, 87L, 0L, 21L],
       [6L, 39L, 27L, 85L, 72L, 11L, 82L, 54L, 12L, 33L],
       [79L, 67L, 10L, 82L, 43L, 87L, 60L, 86L, 23L, 25L],
       [7L, 38L, 43L, 17L, 64L, 72L, 9L, 96L, 66L, 44L],
       [8L, 93L, 42L, 11L, 87L, 46L, 60L, 58L, 86L, 23L],
       [80L, 33L, 22L, 48

In [936]:
np.sum(np.abs(similarity) > 0)

1874161

In [940]:
np.sum(np.abs(similarity) > 1e-5)

800925

In [802]:
sim2 = fast_similarity(ndmat)

sim [[  2.22000000e+02   1.00000000e-09   1.50000000e+01 ...,   7.00000000e+01
    1.00000000e-09   9.80000000e+01]
 [  1.00000000e-09   5.74000000e+02   1.00000000e-09 ...,   1.00000000e-09
    1.00000000e-09   1.00000000e-09]
 [  1.50000000e+01   1.00000000e-09   2.02900000e+03 ...,   1.00000000e-09
    1.00000000e-09   2.00000000e+00]
 ..., 
 [  7.00000000e+01   1.00000000e-09   1.00000000e-09 ...,   3.10000000e+01
    1.00000000e-09   3.50000000e+01]
 [  1.00000000e-09   1.00000000e-09   1.00000000e-09 ...,   1.00000000e-09
    5.50000000e+01   1.00000000e-09]
 [  9.80000000e+01   1.00000000e-09   2.00000000e+00 ...,   3.50000000e+01
    1.00000000e-09   3.65100000e+03]]
diag [  222.   574.  2029. ...,    31.    55.  3651.]
[[ 14.89966443  23.9582971   45.04442252 ...,   5.56776436   7.41619849
   60.42350536]]


In [805]:
simnd = coordinate_matrix_to_ndarr(sim)

In [ ]:
pwd

In [829]:
coordinate_matrix_to_ndarr(coordinatematrix_get_row(ndarr_to_coord_array(test_array3), 1))

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.98905039,  0.9516414 ,  0.20273982,  0.20800506]])

In [844]:
row = coordinatematrix_get_row(ndarr_to_coord_array(test_array3), 1)

In [846]:
coordinate_matrix_to_ndarr(row)

array([[ 0.98905039,  0.9516414 ,  0.20273982,  0.20800506]])

In [1089]:
%run cf_spark.py

In [852]:
subreddit_mapper

{1: u'AskReddit',
 2: u'politics',
 3: u'BigBrother',
 4: u'SquaredCircle',
 5: u'The_Donald',
 6: u'gameofthrones',
 7: u'nba',
 8: u'funny',
 9: u'RocketLeagueExchange',
 10: u'videos',
 11: u'worldnews',
 12: u'leagueoflegends',
 13: u'soccer',
 14: u'movies',
 15: u'DotA2',
 16: u'Showerthoughts',
 17: u'news',
 18: u'pics',
 19: u'gaming',
 20: u'MMA',
 21: u'teenagers',
 22: u'todayilearned',
 23: u'hearthstone',
 24: u'pathofexile',
 25: u'pcmasterrace',
 26: u'PUBATTLEGROUNDS',
 27: u'Overwatch',
 28: u'baseball',
 29: u'anime',
 30: u'NYYankees',
 31: u'asoiaf',
 32: u'relationships',
 33: u'Philippines',
 34: u'FireEmblemHeroes',
 35: u'me_irl',
 36: u'aww',
 37: u'gonewild',
 38: u'conspiracy',
 39: u'gifs',
 40: u'BlackPeopleTwitter',
 41: u'DBZDokkanBattle',
 42: u'hiphopheads',
 43: u'rupaulsdragrace',
 44: u'mildlyinteresting',
 45: u'Rainbow6',
 46: u'australia',
 47: u'ethtrader',
 48: u'GlobalOffensive',
 49: u'TheSilphRoad',
 50: u'thebachelor',
 51: u'GlobalOffensiv

In [904]:
top_k_movies(fast_similarity(ndmat, kind = 'item'), subreddit_to_idx('videos', idx_mapper))

[u'videos',
 u'india',
 u'grandorder',
 u'AskReddit',
 u'Warframe',
 u'relationships']

In [880]:
def run_spark_ndarray(ndmat, subreddit):
    """
    ndmat : np.ndarray
    
    row indices: users
    column indices: subreddits
    """
    sim = similarity_matrix(ndarr_to_coord_array(ndmat.T))
    return spark_top_k_subs(sim, subreddit_to_idx(subreddit, idx_mapper), subreddit_mapper)

In [1109]:
idx = 55
row = la.coordinatematrix_get_row(sim, idx)
movie_row = la.coordinate_matrix_to_ndarr(row)[0]
sm = [np.argsort(movie_row)[::-1]]

In [1125]:
sorted(sim.entries.map(lambda entry: entry.i).distinct().collect())

[0L,
 1L,
 2L,
 3L,
 4L,
 5L,
 6L,
 7L,
 8L,
 9L,
 10L,
 11L,
 12L,
 13L,
 14L,
 15L,
 16L,
 17L,
 18L,
 19L,
 20L,
 21L,
 22L,
 23L,
 24L,
 25L,
 26L,
 27L,
 28L,
 29L,
 30L,
 31L,
 32L,
 33L,
 34L,
 35L,
 36L,
 37L,
 38L,
 39L,
 40L,
 41L,
 42L,
 43L,
 44L,
 45L,
 46L,
 47L,
 48L,
 49L,
 50L,
 51L,
 52L,
 54L,
 55L,
 56L,
 57L,
 58L,
 59L,
 60L,
 61L,
 62L,
 63L,
 64L,
 65L,
 66L,
 67L,
 68L,
 69L,
 70L,
 71L,
 72L,
 73L,
 74L,
 75L,
 76L,
 77L,
 78L,
 79L,
 80L,
 81L,
 82L,
 83L,
 84L,
 85L,
 86L,
 87L,
 88L,
 89L,
 90L,
 91L,
 92L,
 93L,
 94L,
 95L,
 96L,
 97L,
 98L,
 99L]

In [1116]:
len(la.coordinatematrix_sort_rows(sim, 6))

99

In [1126]:
%run cf_spark.py

In [1104]:
subreddit_to_idx('Amd', idx_mapper)

55

In [1113]:
list(enumerate(la.coordinatematrix_sort_rows(sim, 6)))

[(0, [0L, 39L, 9L, 62L, 13L, 91L]),
 (1, [1L, 91L, 16L, 15L, 39L, 10L]),
 (2, [2L, 49L, 97L, 27L, 54L, 6L]),
 (3, [3L, 97L, 41L, 28L, 91L, 85L]),
 (4, [4L, 62L, 65L, 96L, 3L, 10L]),
 (5, [5L, 60L, 86L, 51L, 19L, 59L]),
 (6, [6L, 39L, 27L, 85L, 72L, 11L]),
 (7, [7L, 38L, 43L, 17L, 64L, 72L]),
 (8, [8L, 93L, 42L, 11L, 87L, 46L]),
 (9, [9L, 0L, 7L, 65L, 73L, 26L]),
 (10, [10L, 79L, 82L, 1L, 88L, 32L]),
 (11, [11L, 33L, 6L, 14L, 3L, 67L]),
 (12, [12L, 27L, 29L, 6L, 19L, 88L]),
 (13, [13L, 19L, 55L, 0L, 3L, 45L]),
 (14, [14L, 67L, 33L, 11L, 46L, 51L]),
 (15, [15L, 39L, 22L, 26L, 1L, 38L]),
 (16, [16L, 1L, 5L, 26L, 10L, 39L]),
 (17, [17L, 38L, 7L, 43L, 96L, 74L]),
 (18, [18L, 12L, 0L, 72L, 37L, 94L]),
 (19, [19L, 59L, 22L, 13L, 62L, 12L]),
 (20, [20L, 70L, 65L, 55L, 33L, 40L]),
 (21, [21L, 43L, 15L, 65L, 7L, 13L]),
 (22, [22L, 26L, 15L, 80L, 19L, 48L]),
 (23, [23L, 87L, 86L, 39L, 77L, 60L]),
 (24, [24L, 86L, 52L, 30L, 26L, 51L]),
 (25, [25L, 46L, 72L, 44L, 73L, 14L]),
 (26, [26L, 22L, 15L, 4

In [1112]:
la.coordinatematrix_sort_rows(sim, 6)[idx]

[[0L, 39L, 9L, 62L, 13L, 91L],
 [1L, 91L, 16L, 15L, 39L, 10L],
 [2L, 49L, 97L, 27L, 54L, 6L],
 [3L, 97L, 41L, 28L, 91L, 85L],
 [4L, 62L, 65L, 96L, 3L, 10L],
 [5L, 60L, 86L, 51L, 19L, 59L],
 [6L, 39L, 27L, 85L, 72L, 11L],
 [7L, 38L, 43L, 17L, 64L, 72L],
 [8L, 93L, 42L, 11L, 87L, 46L],
 [9L, 0L, 7L, 65L, 73L, 26L],
 [10L, 79L, 82L, 1L, 88L, 32L],
 [11L, 33L, 6L, 14L, 3L, 67L],
 [12L, 27L, 29L, 6L, 19L, 88L],
 [13L, 19L, 55L, 0L, 3L, 45L],
 [14L, 67L, 33L, 11L, 46L, 51L],
 [15L, 39L, 22L, 26L, 1L, 38L],
 [16L, 1L, 5L, 26L, 10L, 39L],
 [17L, 38L, 7L, 43L, 96L, 74L],
 [18L, 12L, 0L, 72L, 37L, 94L],
 [19L, 59L, 22L, 13L, 62L, 12L],
 [20L, 70L, 65L, 55L, 33L, 40L],
 [21L, 43L, 15L, 65L, 7L, 13L],
 [22L, 26L, 15L, 80L, 19L, 48L],
 [23L, 87L, 86L, 39L, 77L, 60L],
 [24L, 86L, 52L, 30L, 26L, 51L],
 [25L, 46L, 72L, 44L, 73L, 14L],
 [26L, 22L, 15L, 47L, 51L, 24L],
 [27L, 29L, 85L, 6L, 12L, 75L],
 [28L, 3L, 27L, 99L, 95L, 81L],
 [29L, 27L, 12L, 49L, 39L, 73L],
 [30L, 74L, 92L, 24L, 5L, 36L],
 [31L, 

In [1050]:
np.argsort(coordinate_matrix_to_ndarr(la.coordinatematrix_get_row(sim, 8))[::-1])

array([[67, 79, 43, 25, 26, 48, 47, 45, 44, 49, 80, 41, 40, 81, 38, 78, 50,
        51, 52, 66, 65, 64, 63, 71, 72, 37, 74, 75, 76, 56, 77, 54, 53, 59,
        36, 34, 68,  1,  2, 97,  4, 96,  6,  7, 95,  9, 94, 92, 91, 90, 89,
        88, 16, 17, 33, 82, 31, 30, 29, 28, 35, 27, 83, 22, 21, 20, 19, 85,
        24, 69,  0, 39, 15,  5, 18, 12, 10, 70, 55, 99, 73, 62, 14, 13, 98,
        61, 84, 32,  3, 57, 23, 86, 58, 60, 46, 87, 11, 42, 93,  8]])

In [1111]:
np.argsort(movie_row)[::-1]

array([55, 33, 40, 92, 52, 20, 13, 44, 75, 69, 56, 91, 84, 26, 14, 81, 97,
       28, 47, 42, 48,  9, 39, 24, 10, 43,  8,  6,  1, 51, 79, 87, 62, 23,
       96, 80,  0, 60, 18, 46, 61,  7, 95,  3, 27, 77, 86, 54, 73, 85,  5,
       12, 57, 11, 22, 17, 68, 93,  2, 16, 21, 99, 70, 25, 19, 98, 15, 66,
       67, 71, 72, 74, 37, 78, 82, 83, 88,  4, 89, 90, 94, 76, 64, 65, 29,
       35, 34, 38, 32, 31, 30, 41, 36, 45, 50, 53, 58, 59, 63, 49])

In [1018]:
run_spark_ndarray(ndmat, 'videos')

[u'videos',
 u'india',
 u'grandorder',
 u'AskReddit',
 u'Warframe',
 u'relationships']

In [905]:
run_spark_ndarray(ndmat, 'videos')

[u'videos',
 u'india',
 u'grandorder',
 u'AskReddit',
 u'Warframe',
 u'relationships']

In [1100]:
spark_top_k_subs(sim, subreddit_to_idx('Amd', idx_mapper), subreddit_mapper)

[u'Amd',
 u'FireEmblemHeroes',
 u'DBZDokkanBattle',
 u'Guildwars2',
 u'buildapc',
 u'teenagers']

In [1128]:
%run cf_spark.py

In [ ]:
spark_top_k_subs2(sim, subreddit_to_idx('Amd', idx_mapper), subreddit_mapper)

In [811]:
np.all(np.isclose(simnd, sim2))

True

In [408]:
def func1(ndmat):
    ndmat = ndmat.copy()
    ndmat /= (epsilon + np.std(ndmat, axis = 0))
    ndmat /= (epsilon + np.std(ndmat.T, axis = 1).T)
    return ndmat

In [411]:
matfuncs = [func1]
def findtop_allmodels(sub_name):
    ndmat = coordinate_matrix_to_ndarr(tf_ij)
    ndmat = ndmat.T
    ndmat = ndmat[1:, 1:]
    
    def do_one(func, ndmat):
        ndmat = func(ndmat)
        train, test = train_test_split(ndmat)
        similarity = fast_similarity(train)

        item_similarity = fast_similarity(train, kind = 'item')
        print top_k_movies(item_similarity, subreddit_to_idx(sub_name), k = 10)
    [do_one(f, ndmat) for f in matfuncs]

In [426]:
import pickle

In [427]:
import md5

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  if __name__ == '__main__':


In [873]:
def generate_ndmat():
    epsilon = 1e-9
    ndmat = coordinate_matrix_to_ndarr(tf_ij)
    ndmat = ndmat.T
    ndmat = ndmat[1:, 1:]

    #ndmat = np.mean(ndmat, axis = 0)
    ndmat /= (epsilon + np.std(ndmat, axis = 0))
    ndmat /= (epsilon + np.std(ndmat.T, axis = 1).T)
    
    print md5.md5(pickle.dumps(train)).digest()
    return ndmat

In [1009]:
epsilon = 1e-9
ndmat = coordinate_matrix_to_ndarr(tf_ij)
ndmat = ndmat.T
ndmat = ndmat[1:, 1:]

#ndmat = np.mean(ndmat, axis = 0)
ndmat /= (epsilon + np.std(ndmat, axis = 0))
ndmat /= (epsilon + np.std(ndmat.T, axis = 1).T)

train, test = train_test_split(ndmat)
similarity = fast_similarity(ndmat)

item_similarity = fast_similarity(ndmat, kind = 'item')

md5.md5(pickle.dumps(train)).digest()

'\x1b\xbb\xc46 O\xe3\xdb\x83\xb2\x15\x84Rt\x00\x06'

In [266]:
subreddit_mapper

{1: u'AskReddit',
 2: u'politics',
 3: u'BigBrother',
 4: u'SquaredCircle',
 5: u'The_Donald',
 6: u'gameofthrones',
 7: u'nba',
 8: u'funny',
 9: u'RocketLeagueExchange',
 10: u'videos',
 11: u'worldnews',
 12: u'leagueoflegends',
 13: u'soccer',
 14: u'movies',
 15: u'DotA2',
 16: u'Showerthoughts',
 17: u'news',
 18: u'pics',
 19: u'gaming',
 20: u'MMA',
 21: u'teenagers',
 22: u'todayilearned',
 23: u'hearthstone',
 24: u'pathofexile',
 25: u'pcmasterrace',
 26: u'PUBATTLEGROUNDS',
 27: u'Overwatch',
 28: u'baseball',
 29: u'anime',
 30: u'NYYankees',
 31: u'asoiaf',
 32: u'relationships',
 33: u'Philippines',
 34: u'FireEmblemHeroes',
 35: u'me_irl',
 36: u'aww',
 37: u'gonewild',
 38: u'conspiracy',
 39: u'gifs',
 40: u'BlackPeopleTwitter',
 41: u'DBZDokkanBattle',
 42: u'hiphopheads',
 43: u'rupaulsdragrace',
 44: u'mildlyinteresting',
 45: u'Rainbow6',
 46: u'australia',
 47: u'ethtrader',
 48: u'GlobalOffensive',
 49: u'TheSilphRoad',
 50: u'thebachelor',
 51: u'GlobalOffensiv

In [304]:
subreddit_mapper

{1: u'AskReddit',
 2: u'politics',
 3: u'BigBrother',
 4: u'SquaredCircle',
 5: u'The_Donald',
 6: u'gameofthrones',
 7: u'nba',
 8: u'funny',
 9: u'RocketLeagueExchange',
 10: u'videos',
 11: u'worldnews',
 12: u'leagueoflegends',
 13: u'soccer',
 14: u'movies',
 15: u'DotA2',
 16: u'Showerthoughts',
 17: u'news',
 18: u'pics',
 19: u'gaming',
 20: u'MMA',
 21: u'teenagers',
 22: u'todayilearned',
 23: u'hearthstone',
 24: u'pathofexile',
 25: u'pcmasterrace',
 26: u'PUBATTLEGROUNDS',
 27: u'Overwatch',
 28: u'baseball',
 29: u'anime',
 30: u'NYYankees',
 31: u'asoiaf',
 32: u'relationships',
 33: u'Philippines',
 34: u'FireEmblemHeroes',
 35: u'me_irl',
 36: u'aww',
 37: u'gonewild',
 38: u'conspiracy',
 39: u'gifs',
 40: u'BlackPeopleTwitter',
 41: u'DBZDokkanBattle',
 42: u'hiphopheads',
 43: u'rupaulsdragrace',
 44: u'mildlyinteresting',
 45: u'Rainbow6',
 46: u'australia',
 47: u'ethtrader',
 48: u'GlobalOffensive',
 49: u'TheSilphRoad',
 50: u'thebachelor',
 51: u'GlobalOffensiv

In [333]:
top_k_movies(item_similarity, subreddit_to_idx(u'videos'), k = 10)

[u'videos',
 u'anime',
 u'movies',
 u'Amd',
 u'gaming',
 u'hockey',
 u'hearthstone',
 u'rickandmorty',
 u'news',
 u'ffxiv']

In [444]:
findtop_allmodels('videos')

[u'videos', u'movies', u'anime', u'Amd', u'gaming', u'pics', u'asoiaf', u'rickandmorty', u'AdviceAnimals', u'nba']


In [530]:
import cf_numpy
ndmat = coordinate_matrix_to_ndarr(tf_ij)
ndmat = ndmat.T
ndmat = ndmat[1:, 1:]
subreddit_mapper = dict(act.rdd.map(lambda entry: (entry.ordered_id, entry.subreddit)).collect())

In [535]:
%pdb

Automatic pdb calling has been turned OFF


In [541]:
ndmat = coordinate_matrix_to_ndarr(tf_ij)

In [543]:
train_test_split(ndmat)

ValueError: a must be non-empty

In [537]:
epsilon = 1e-9
ndmat = ndmat.T
ndmat = ndmat[1:, 1:]

# TODO: play with this
ndmat /= (epsilon + np.std(ndmat, axis = 0))
ndmat /= (epsilon + np.std(ndmat.T, axis = 1).T)

train, test = train_test_split(ndmat)
state['item_similarity_full'] = fast_similarity(ndmat, kind = 'item')
state['item_similarity_sampled'] = fast_similarity(train, kind = 'item')
state['subreddit_mapper'] = subreddit_mapper
state['idx_mapper'] = {v: k for k, v in subreddit_mapper.iteritems()}

ValueError: Cannot take a larger sample than population when 'replace=False'

In [567]:
reload(cf_numpy)
cf_numpy.init(ndmat, subreddit_mapper)

In [571]:
cf_numpy.related_subs('movies')

[u'movies',
 u'MMA',
 u'Amd',
 u'AskReddit',
 u'SquaredCircle',
 u'australia',
 u'Games',
 u'teslamotors',
 u'politics',
 u'funny']

In [523]:
top_k_movies(item_similarity, subreddit_to_idx(u'news'), k = 10)

[u'news',
 u'politics',
 u'gameofthrones',
 u'Overwatch',
 u'worldnews',
 u'BlackPeopleTwitter',
 u'DotA2',
 u'funny',
 u'science',
 u'relationships']

In [524]:
top_k_movies(item_similarity, subreddit_to_idx(u'leagueoflegends'), k = 10)

[u'leagueoflegends',
 u'FireEmblemHeroes',
 u'nba',
 u'DotA2',
 u'SquaredCircle',
 u'2007scape',
 u'RocketLeagueExchange',
 u'nfl',
 u'Bitcoin',
 u'ethtrader']

In [297]:
predictions = predict_nobias(train, item_similarity, kind = 'item')

In [300]:
predictions.shape

(227, 100)

In [258]:
idx_to_subreddit(90)

u'FashionReps'

In [224]:
predictions.shape

(227, 101)

In [337]:
a_ij.entries.count()

465503

In [103]:
tf_ij.numCols()

43758L

In [323]:
entropy_i.numRows()

17045L

In [ ]:
logp_ij = coordinateMatrixElementwise

In [203]:
activity_df.toPandas()

rid  activity
0     1         1
1     2         1
2     3         1
3     4         2
4     5         1
5     6       295
6     7        32
7     8         9
8     9         4
9    10         3
10   11         5
11   12         4
12   13         4
13   14         7
14   15         5
15   16         5
16   17         3
17   18         4
18   19         1
19   20         1
20   21         2
21   22       132
22   23       444
23   24        10
24   25        14
25   26         9
26   27         1
27   28         3
28   29        14
29   30        18
30   31      1665
31   32        24
32   33         1
33   34        74
34   35        27
35   36         1
36   37         1
37   38        53
38   39         2
39   40        10
40   41      7068
41   42        25
42   43         1
43   44        13
44   45       512
45   46         3
46   47        84
47   48       132
48   49        10
49   50         5
50   51         1
51   52        16
52   53       154
53   54      4449
54   55         5
55   56        23
56   57        10
57   58         2
58   59        29
59   60         1
    ...       ...

[17044 rows x 2 columns]

In [15]:
from operator import add

# TODO: check that zero entries are correctly filtered
def coordinateMatrixMultiply(leftmat, rightmat):
    m = leftmat.entries.map(lambda entry: (entry.j, (entry.i, entry.value)))
    n = rightmat.entries.map(lambda entry: (entry.i, (entry.j, entry.value)))
    product_entries = m.join(n)\
    .map(lambda tup: ((tup[1][0][0], tup[1][1][0]), (tup[1][0][1] * tup[1][1][1])))\
    .reduceByKey(add)\
    .map(lambda record: MatrixEntry(record[0][0], record[0][1], record[1]))
    
    return pyspark.mllib.linalg.distributed.CoordinateMatrix(product_entries)

In [16]:
def coordinateMatrixAdd(leftmat, rightmat, scalar):
    """
    Return leftmat + scalar * rightmat
    """
    m = leftmat.entries.map(lambda entry: ((entry.i, entry.j), entry.value))
    n = rightmat.entries.map(lambda entry: ((entry.i, entry.j), scalar * entry.value))
    matsum = m.fullOuterJoin(n)\
    .map(lambda tup: MatrixEntry(tup[0][0], tup[0][1],
                                 reduce(add, filter(lambda elt: elt is not None, tup[1]))))
    
    #return matsum
    return pyspark.mllib.linalg.distributed.CoordinateMatrix(matsum)

In [360]:
test_vec = np.array([[1,1,0]]).T
test_vec2 = np.array([[1,0,0]]).T

In [356]:
coordinate_vector_matrix_norm(ndarr_to_coord_array(test_vec))

1.4142135623730951

In [665]:
sort_row_indices_by_distance(a_ij, coordinatematrix_get_row(a_ij, 37))

[33L,
 3L,
 36L,
 6L,
 39L,
 9L,
 42L,
 12L,
 45L,
 15L,
 48L,
 18L,
 51L,
 21L,
 54L,
 24L,
 57L,
 27L,
 30L,
 1L,
 34L,
 4L,
 37L,
 7L,
 40L,
 10L,
 43L,
 13L,
 46L,
 16L,
 49L,
 19L,
 52L,
 22L,
 55L,
 25L,
 58L,
 28L,
 31L,
 32L,
 2L,
 35L,
 5L,
 38L,
 8L,
 41L,
 11L,
 44L,
 14L,
 47L,
 17L,
 50L,
 20L,
 53L,
 23L,
 56L,
 26L,
 59L,
 29L]

In [ ]:
sort_row_indices_by_distance()

In [484]:
test_array5 = 2 * np.array([[1, 0, 0], [1, 1, 0], [0, 0,  1]])
vec = 2 * np.array([[1, 1, 0.001]])

In [487]:
cm = ndarr_to_coord_array(test_array5)
cv = ndarr_to_coord_array(vec)

In [563]:
td = coordinatematrix_get_row(cmat, 8797)

In [564]:
td.entries.count()

1

In [537]:
sort_row_indices_by_distance(cm, cv)

[1L, 0L, 2L]

In [532]:
v = Vectors.sparse(3, [(1, 1), (2, 1)])

In [533]:
v.norm(2)

1.4142135623730951

In [492]:
cv.entries.map(lambda entry: (entry.j, entry.value)).collect()

[(0L, 2.0), (1L, 2.0), (2L, 0.002)]

In [599]:
v = ndarray_to_sparse_vector(np.zeros(5))

In [600]:
sparse_vector_to_ndarray(v)

array([ 0.,  0.,  0.,  0.,  0.])

In [495]:
v = coordinatematrix_to_sparse_vector(cv)

In [466]:
mat_j.fullOuterJoin(vec_j).map(lambda tup: (tup[1][0][0], (tup[1][0][1] - tup[1][1])**2)).collect()

[(1L, 0.0), (0L, 0.0), (1L, 0.0), (2L, 3.992004)]

In [454]:
mat_j.join(vec_j).map(lambda tup: (tup[1][0][0], (tup[1][0][1] - tup[1][1])**2)).reduceByKey(add).collect()

[(0L, 0.0), (1L, 0.0)]

In [453]:
mat_j.join(vec_j).map(lambda tup: (tup[1][0][0], (tup[1][0][1] - tup[1][1])**2)).reduceByKey(add)\
    .map(lambda tup: (tup[1], tup[0])).sortByKey().map(lambda tup: tup[1]).collect()

[0L, 1L]

In [439]:
ndarr_to_coord_array(test_array2).entries.map(lambda entry: (entry.i, [(entry.i, entry.j)]))\
.reduceByKey(add).collect()

[(0L, [(0L, 0L), (0L, 1L), (0L, 2L)]),
 (1L, [(1L, 0L), (1L, 2L), (1L, 3L)]),
 (2L, [(2L, 2L), (2L, 3L)])]

In [361]:
coordinate_matrix_vector_l2(ndarr_to_coord_array(test_vec), ndarr_to_coord_array(test_vec))

0.0

In [371]:
vec1, vec2 = ndarr_to_coord_array(test_vec), ndarr_to_coord_array(test_vec2)

In [372]:
norm1, norm2 = map(coordinate_vector_matrix_norm, [vec1, vec2])

vec1normed = coordinateMatrixScalarMult(vec1, 1./norm1)
vec2normed = coordinateMatrixScalarMult(vec2, 1./norm2)

diff = coordinateMatrixAdd(vec1normed, vec2normed, -1.)

In [373]:
diff.entries.collect()

[MatrixEntry(0, 0, -0.292893218813), MatrixEntry(1, 0, 0.707106781187)]

In [380]:
coordinate_matrix_vector_l2(ndarr_to_coord_array(test_vec), ndarr_to_coord_array(2 * test_vec2))

0.76536686473017945

In [654]:
v.__dict__

{'indices': array([], dtype=int32),
 'size': 5,
 'values': array([], dtype=float64)}

In [379]:
np.linalg.norm(test_vec.T[0] / np.linalg.norm(test_vec) - test_vec2.T[0] / np.linalg.norm(test_vec2))

0.76536686473017945

In [375]:
mat = ndarr_to_coord_array(test_array2)
mat.entries.filter(lambda entry: entry.i == 2).map(lambda entry: collect()

SyntaxError: invalid syntax (<ipython-input-375-dc50cd5dbed2>, line 2)

Implement LSA

Test stuff

In [94]:
test_coordmat2 = ndarr_to_coord_array(test_array2)

In [97]:
test_coordmat2.entries.filter(lambda entry: entry.value != 0).collect()

[MatrixEntry(0, 0, 1.0),
 MatrixEntry(0, 1, 2.0),
 MatrixEntry(0, 2, 3.0),
 MatrixEntry(1, 0, 4.0),
 MatrixEntry(1, 2, 6.0),
 MatrixEntry(1, 3, 1.0),
 MatrixEntry(2, 2, 8.0),
 MatrixEntry(2, 3, 2.0)]

In [244]:
vec = ndarr_to_coord_array(np.array([[2, 2, 2, 2]]))
mat = ndarr_to_coord_array(np.ones((4, 4)))

m = mat.entries.map(lambda entry: (entry.i, (entry.j, entry.value)))
v = vec.entries.map(lambda entry: (entry.i, (entry.j, entry.value)))
matdiv = m.join(v).map(lambda tup: MatrixEntry(tup[0], tup[1][0][0], float(tup[1][0][1]) / tup[1][1][1]))

In [263]:
eval_matrix_binop(2 * np.ones((4, 4)), 2 * np.ones((4, 4)), coordinate_matrix_elementwise_matrix_multiplication)

(<pyspark.mllib.linalg.distributed.CoordinateMatrix at 0x7fde2b3eba90>,
 array([[ 4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.]]))

In [269]:
sumjtest = coordinate_matrix_sumj(ndarr_to_coord_array(np.ones((3, 4))))

In [270]:
coordinate_matrix_to_ndarr(sumjtest)

array([[ 4.],
       [ 4.],
       [ 4.]])

In [296]:
test_array2

array([[ 1.,  2.,  3.,  0.],
       [ 4.,  0.,  6.,  1.],
       [ 0.,  0.,  8.,  2.]])

In [300]:
eval_matrix_binop(test_array2, np.array([[2, 3, 4]]).T, coordinatematrix_multiply_vector_elementwise)

(<pyspark.mllib.linalg.distributed.CoordinateMatrix at 0x7fde20ca84d0>,
 array([[  2.,   4.,   6.,   0.],
        [ 12.,   0.,  18.,   3.],
        [  0.,   0.,  32.,   8.]]))

In [351]:
coordinate_matrix_row(ndarr_to_coord_array(test_array2), 1).entries.collect()

[MatrixEntry(0, 0, 4.0), MatrixEntry(0, 2, 6.0), MatrixEntry(0, 3, 1.0)]

In [125]:
test_add()
test_multiply()

In [78]:
coordinate_matrix_to_ndarr(coordinateMatrixScalarMult(ndarr_to_coord_array(test_array2), 1.5))

array([[  1.5,   3. ,   4.5,   0. ],
       [  6. ,   0. ,   9. ,   1.5],
       [  0. ,   0. ,  12. ,   3. ]])

In [92]:
coordinate_matrix_to_ndarr(coordinateMatrixElementwise(ndarr_to_coord_array(test_array2), lambda n: np.log(n)))

array([[ 0.        ,  0.69314718,  1.09861229,        -inf],
       [ 1.38629436,        -inf,  1.79175947,  0.        ],
       [       -inf,        -inf,  2.07944154,  0.69314718]])

In [93]:
test_array2

array([[ 1.,  2.,  3.,  0.],
       [ 4.,  0.,  6.,  1.],
       [ 0.,  0.,  8.,  2.]])

SVD implementation

In [80]:
from random import normalvariate

In [85]:
cmat.numCols()

347112L

In [83]:
from random import normalvariate
def random_unit(n):
    vec = np.array([normalvariate(0, 1) for _ in range(n)])
    return vec / np.linalg.norm(vec)

def SVD_1D(A, threshold = 1e-10):
    """
    A : CoordinateMatrix
    """
    n, m = A.numRows(), A.numCols()
    x = random_unit(m)
    # TODO finish this

In [ ]:
import numpy as np
from numpy.linalg import norm

def svd_1d(A, epsilon=1e-10):
    ''' The one-dimensional SVD '''
    n, m = A.shape
    x = randomUnitVector(m)
    lastV = None
    currentV = x
    B = np.dot(A.T, A)
 
    iterations = 0
    while True:
        iterations += 1
        lastV = currentV
        currentV = np.dot(B, lastV)
        currentV = currentV / norm(currentV)
 
        if abs(np.dot(currentV, lastV)) > 1 - epsilon:
            print("converged in {} iterations!".format(iterations))
            return currentV

In [62]:
m2 = coordinateMatrixAdd(cmat, cmat, -2)

In [64]:
m2.entries.take(2)

[MatrixEntry(3, 9, -2.0), MatrixEntry(8, 4, -1.0)]

In [25]:
matsum = coordinateMatrixAdd(ndarr_to_coord_array(test_array3), ndarr_to_coord_array(test_array3), -2)

In [29]:
cmat = CoordinateMatrix(bare_occurrences.rdd.map(tuple))

In [43]:
cmat.entries.take(2)

[MatrixEntry(1, 176355, 1.0), MatrixEntry(2, 2547, 1.0)]

In [74]:
mul.entries.count()

595811

In [41]:
cmat.entries.count()

475392

In [45]:
cmb = cmat.toBlockMatrix()

In [47]:
cmi = cmb.toIndexedRowMatrix()

In [51]:
row = cmi.rows.take(1)

[IndexedRow(3558, (347112,[54015,294324],[1.0,2.0]))]

In [144]:
sqlContext.sql("""
select max(uid)
from occurrences
""").toPandas()

max(uid)
0    341578

[1 rows x 1 columns]

In [57]:
occurrences.toPandas()

subreddit                author  tally     uid  rid
0              zyramains          TricolorStar      1  176355    1
1                 zylzon       youknowitsyaboy      1    2547    2
2             zweiteliga               Saminka      1  206115    3
3                 zurich          maxwellmaxen      2   72503    4
4                    zsh              __soddit      1  159502    5
5               zootopia        thawed_caveman      2   22475    6
6               zootopia           speisekarte     11   29937    6
7               zootopia          rodrigogirao      6   42380    6
8               zootopia             phobos136      4   53058    6
9               zootopia      midnightopheliac      9   70104    6
10              zootopia            mashinjams      2   73325    6
11              zootopia              maks_orp      1   74585    6
12              zootopia            howieeiwoh      2  100894    6
13              zootopia                ggctuk      1  108920    6
14              zootopia             [deleted]     13  160457    6
15              zootopia   ZootopiaNewsNetwork      6  160767    6
16              zootopia             Yert19943     14  163631    6
17              zootopia            WildeHopps      9  166926    6
18              zootopia      Vulpes_V_Sapiens     57  169715    6
19              zootopia      UneventfulWaffle      4  173379    6
20              zootopia        ThatTrashPanda     14  185928    6
21              zootopia         Stalwartheart      5  193799    6
22              zootopia           Rutgerman95      1  208286    6
23              zootopia               Qwerky3      4  216356    6
24              zootopia          Pax_et_Bonum      5  223292    6
25              zootopia        OmegaBartender      1  227854    6
26              zootopia             LotharHex     10  249955    6
27              zootopia           LiquidSpear      9  251725    6
28              zootopia          Lapis_Mirror      5  254538    6
29              zootopia      JacquesTheBird11     17  267391    6
30              zootopia               INCG779      4  273570    6
31              zootopia         HumanKleinJar      6  274928    6
32              zootopia           Gambler_Tut     25  285881    6
33              zootopia                Galgus     19  285952    6
34              zootopia               Frozia_      3  287534    6
35              zootopia  EvilStevilTheKenevil      1  293754    6
36              zootopia     DrunkenShitposter      1  299010    6
37              zootopia                DL2828      5  308901    6
38              zootopia       Cleaningcaptain      3  314387    6
39              zootopia       Chandeliercrown      5  317076    6
40              zootopia            CatsShadow      8  317759    6
41              zootopia      BunnyMakingAMark      2  321433    6
42              zootopia       A_Stinking_Hobo      1  340935    6
43             zoophilia        the_egoldstein      4   22058    7
44             zoophilia          electricfoxx      4  118713    7
45             zoophilia              ckgjkjj6      3  134005    7
46             zoophilia              caikgoch      5  138922    7
47             zoophilia             [deleted]      2  160457    7
48             zoophilia         AutoModerator      1  332256    7
49             zoophilia           AmoreBestia     12  336724    7
50             zoophilia                 30-30      1  344251    7
51  zooolanderconspiracy           zjwflippers      6     680    8
52  zooolanderconspiracy           daunbugless      3  127323    8
53               zombies            xmadison84      3    4184    9
54               zombies             [deleted]      1  160457    9
55             zombicide             Stormcast      3  192430   10
56           zoieburgher              jdardick      1   92373   11
57           zoieburgher           OrganaChard      3  226841   11
58           zoieburgher         MUFCLEGEND123      1  247782 

In [89]:
# TODO: why doesn't this match rid?
cmat.numRows()

17085L

In [71]:
import numpy as np

In [74]:
np.array(df['tally']).min()

-632

In [69]:
sqlContext.sql("""
select author, subreddit, sum (score)
from test
group by author, subreddit
""").toPandas()

author              subreddit  sum(score)
0          FormulaXDGame               formula1          31
1            HelluvaDeke                 gaming           2
2           WhoKnowsWho2                xboxone          70
3            listentohim        DBZDokkanBattle           1
4               sevenzig               AskOuija          10
5              LumpyPick        leagueoflegends           4
6        volvostupidshit            Philippines           6
7        i_fuck_goats777              AskReddit           2
8        Ineeditunesalot          battlefield_4          11
9        martianlawrence                 movies          11
10       Capt_Tommy_Bags            nottheonion           1
11          KnightVision                 loseit           2
12                l4stfr        gaymersgonewild           1
13             [deleted]                 leaves          27
14            Hansolo510           IndoorGarden           1
15         FlightlessFly               CasualUK           8
16             [deleted]                    CFB          72
17   toolongdidntreadlol           albiononline          11
18        notlaurensorry          AdviceAnimals          30
19             [deleted]            thebachelor         544
20   PAPERCUT_MY_URETHRA             BigBrother          14
21                8bitid                   news           2
22      WillGriggsOnFire                 soccer           5
23         notyet_aTwunk             askgaybros          33
24         LithiumEnergy      EverythingScience           0
25         GeorgFestrunk           TheSilphRoad          16
26             Lichewitz               ihavesex           3
27               sal9002        whatisthisthing          40
28            shutupjoey          gameofthrones           2
29              RMaximus                Gunners           1
30      illuminaughtiess                 loseit          14
31              BetaKush                   pics           1
32             phernoree                    nba           9
33     uhhhhhhhhhhhhhidk                 fakeid           2
34     justalittlebird88          relationships           2
35  YodaGandalfDumbled0r  Chinese_Bootleg_Memes           8
36          Digital_loop                 gaming          12
37    iamtheultimateshoe              AntiJokes           1
38           andrewcooke             cyclocross           5
39              wratther               Electrum           2
40            qldmaroon7          SquaredCircle          54
41          PieceDigital          StreetFighter           4
42              pwnsauce              SeattleWA          12
43                Kim147        climateskeptics          14
44              Cadinsor             Wetshaving           3
45          MINIMAN10001                 MMORPG           4
46              GameVoid               Teachers           1
47            sir_writer              AskReddit           8
48     sugar_free_haribo             The_Donald           1
49               jfchops            hometheater           4
50      Pappy_StrideRite        DarkBitsNPieces           2
51              Djinnobi     BlackPeopleTwitter           8
52              dpeeeezy                   FIFA          -3
53        schoolairplane          SquaredCircle          32
54            SilverMars          IgnorantImgur          21
55             fivejazz5                    DIY           3
56     RetainedByLucifer             The_Donald           9
57               SikeRed     EatCheapAndHealthy           4
58        EdosianGeneral                 TrekRP           2
59               beardko              OWConsole           4
                     ...                    ...         ...

[475392 rows x 3 columns]

In [78]:
sj.toPandas()

author author_cakeday author_flair_css_class  \
0         stunt_penguin           None                   None   
1             [deleted]           None                   None   
2                 69ing           None                   None   
3        ArchadianJudge           None         Archadianflair   
4              sglville           None                   None   
5           NEWORLDODOR           None                   None   
6             zachwad22           None                   None   
7       lurker4lyfe6969           None                   None   
8        SuburbanStoner           None                   None   
9            ensanguine           None                   None   
10               p-wing           None                          
11            Lolonnais           None         pennant teamnp   
12  askingquestionsblog           None                   None   
13          Newbieshoes           None                   None   
14            sking1225           None                 cmpunk   
15   PM_ME_WEIRD_SMILES           None                   None   
16            Alvarez09           None                   None   
17          Synchrotr0n           None                   None   
18           rudolphsb9           None                   None   
19       arbuthnot-lane           None                   None   
20               d3fect           None                          
21       relator_fabula           None             JerseyLogo   
22               Knonkh           None                 AUDIEU   
23             zxj4k3xz           None                          
24            [deleted]           None                   None   
25            [deleted]           None                   None   
26       mcgregorshakes           None                   None   
27              kamekai           None                   None   
28          KarlOskar12           None                   None   
29       CrimsonStone72           None                     SL   
30            marflow75           None                   None   
31             Jechtael           None                   None   
32         ChaoticLogix           None                   None   
33                T1PPY           None                   None   
34           MdMa4Me247           None                   None   
35           Kanyeezy96           None                   None   
36             19720703           None                   None   
37         flyingmunkie           None                          
38          spartag00se           None                   None   
39         mrhomeless97           None                   None   
40               Asquil           None                   None   
41            [deleted]           None                   None   
42         whammydiddle           None                redsox7   
43             horsodox           None                   None   
44            [deleted]           None                   None   
45             telebofh           None                   None   
46     sagittariuscraig           None                   None   
47     PM_YOUR_HARDCOCK           None                   None   
48         sarahfearing           None                   None   
49              twojs1b           None                   None   
50              EBJ1990           None            sheet3pos21   
51              x00drew           None                   xbox   
52              mikemnm           None                   None   
53          Blacktivism           None                   None   
54          Inoidzervit           None                   None   
55             Astonsfw           None                   None   
56    the_orange_wizard           None                   None   
57        noonespecific           None                 glitch   
58            CMikeHunt           None                   DART   
59           Cosmodious           None                   None   
                    ...            ...              

In [27]:
rawDF = sqlContext.read.json("s3n://reddit-comments/2015/RC_2015-05", StructType(fields)).persist(StorageLevel.MEMORY_AND_DISK_SER)

In [28]:
rawDF.registerTempTable('comments')

In [574]:
sj.select

<bound method DataFrame.select of DataFrame[author: string, score: bigint, controversiality: bigint, subreddit: string]>